import axios from 'axios';
import { API_URL, getAxiosConfig } from '../config';

export interface InvoiceItem {
    itemDescription: string;
    hsnSac: string;
    quantity: number;
    unit: string;
    rate: number;
    watt?: number;
    isSolarPanel?: boolean;
    discount: number;
    amount: number;
    // ================================
// ADD IN InvoiceItem INTERFACE
// ================================

id?: string;

description?: string;

subDescription?: string;

itemName?: string;

specification?: string;

make?: string;

hsn?: string;

qty?: number;

gstRate?: number;
}

export interface Invoice {
    id: string; // generated by backend
    companyName: string;
    invoiceNumber: string;
    invoiceDate: string;

    // Unified Fields
    currency: 'INR' | 'USD';
    category: 'DOMESTIC' | 'EXPORT' | 'TAX_INVOICE';
    customerEmail?: string;
    salesPersonName?: string;
    salesPersonPhone?: string;

    gstinNumber: string;
    paymentStatus: 'PENDING' | 'PAID' | 'PARTIAL' | 'OVERDUE';
    modeOfDispatch: string;
    transportThrough?: string;
    trackingNumber?: string;
    remarks?: string;
    customerName: string;
    customerAddress: string;
    customerContact: string;
    customerGstinUin: string;
    recipientName: string;
    shippingAddress: string;
    stateCode: string;
    placeOfSupply: string;
    items: InvoiceItem[];
    netAmount: number;
    cashDiscount: number;
    cgst: number;
    sgst: number;
    roundOff: number;
    grandTotalPayable: number;
    amountInWords: string;
    bankName: string;
    accountNumber: string;
    ifscCode: string;
    termsAndConditions: string;
    pdfFilePath?: string;
    status?: string;
    rejectionReason?: string;
    createdAt?: string;
    updatedAt?: string;
    isProforma?: boolean;
    advancedEnabled?: boolean;
additionalAmount?: number;
// ================================
// ADD IN Invoice INTERFACE
// ================================

fromCompanyName?: string;

fromGstin?: string;

customerPhone?: string;

customerGstin?: string;

bankAccountNo?: string;

bankIfsc?: string;

netPayableAmount?: number;

paidAmount?: number;

remainingAmount?: number;

paidType?: string;

paymentType?: string;

serviceType?: string;

systemCapacityKw?: number;

gstNumber?: string;
invoiceType?: string;

}

export const getInvoices = async (filters?: any): Promise<Invoice[]> => {
    const response = await axios.get(`${API_URL}/invoices`, {
        ...getAxiosConfig(),
        params: filters
    });
    return response.data.data;
};

export const getInvoiceById = async (id: string): Promise<Invoice> => {
    const response = await axios.get(`${API_URL}/invoices/${id}`, getAxiosConfig());
    return response.data.data;
};

export const createInvoice = async (invoiceData: Partial<Invoice>): Promise<Invoice> => {
    const response = await axios.post(`${API_URL}/invoices`, invoiceData, getAxiosConfig());
    return response.data.data;
};

export const updateInvoice = async (id: string, invoiceData: Partial<Invoice>): Promise<Invoice> => {
    const response = await axios.put(`${API_URL}/invoices/${id}`, invoiceData, getAxiosConfig());
    return response.data.data;
};

export const deleteInvoice = async (id: string): Promise<void> => {
    await axios.delete(`${API_URL}/invoices/${id}`, getAxiosConfig());
};


export const getInvoiceDownloadUrl = async (id: string): Promise<{ url: string }> => {
    const response = await axios.get(`${API_URL}/invoices/${id}/download-invoice`, {
        ...getAxiosConfig(),
        responseType: 'blob'
    });

    // If backend sends blob
    if (response.data instanceof Blob) {
        const url = window.URL.createObjectURL(response.data);
        return { url };
    }

    // If backend sends URL
    return { url: response.data.url };
};

export const getNextInvoiceNumber = async (companyName: string): Promise<string> => {
    const response = await axios.get(`${API_URL}/invoices/next-number`, {
        ...getAxiosConfig(),
        params: { companyName }
    });
    return response.data.nextInvoiceNumber;
};

// Get next export estimate number based on company
export const getNextExportEstimateNumber = async (companyName: string): Promise<string> => {
    const response = await axios.get(`${API_URL}/invoices/next-export-number`, {
        ...getAxiosConfig(),
        params: { companyName }
    });
    return response.data.nextExportNumber;
};

// [NEW] Send Invoice Email
export const sendInvoiceEmail = async (id: string): Promise<{ success: boolean; message: string }> => {
    const response = await axios.post(`${API_URL}/invoices/${id}/send-email`, {}, getAxiosConfig());
    return response.data;
};

// [NEW] Get Delivery Date Preview
export const getDeliveryPreviewUrl = async (id: string, date: string): Promise<{ url: string }> => {
    // Returns a temporary signed URL or triggers a download
    // For a preview, we might get a Blob, but let's assume URL for now as per other patterns
    const response = await axios.get(`${API_URL}/invoices/${id}/delivery-preview?date=${date}`, {
        ...getAxiosConfig(),
        responseType: 'blob' // Expecting a PDF blob if it's a direct download, but if it returns a URL:
    });

    // If backend returns a stream/blob for direct download:
    const url = window.URL.createObjectURL(response.data);
    return { url };
};

export const convertToTaxInvoice = async (

    id: string,

    data: any

): Promise<Invoice> => {

    const response =
        await axios.patch(

            `${API_URL}/invoices/${id}/tax-invoice`,

            data,

            getAxiosConfig()
        );

    return response.data.data;
};
// [NEW] Create Production Task from Invoice
export const createProductionFromInvoice = async (invoiceId: string, productionData: any) => {
    const response = await axios.post(
        `${API_URL}/invoices/${invoiceId}/create-production-task`,
        productionData,
        getAxiosConfig()
    );
    return response.data;
};
// [NEW] Invoice Proofs
export const uploadInvoiceProof = async (invoiceId: string, file: File, type: string) => {
    const formData = new FormData();
    formData.append('file', file);
    formData.append('type', type);

    const response = await axios.post(
        `${API_URL}/invoices/${invoiceId}/proofs`,
        formData,
        getAxiosConfig()
    );
    return response.data;
};

export const getInvoiceProofs = async (invoiceId: string) => {
    const response = await axios.get(
        `${API_URL}/invoices/${invoiceId}/proofs`,
        getAxiosConfig()
    );
    return response.data;
};

// export const getInvoicePreviewUrl = async (id: string): Promise<{ url: string }> => {
//     const response = await axios.get(`${API_URL}/invoices/${id}/download-sales-invoice`, {
//         ...getAxiosConfig(),
//         responseType: 'blob'
//     });

//     const url = window.URL.createObjectURL(new Blob([response.data], { type: 'application/pdf' }));
//     return { url };
// };

export const getInvoicePreviewUrl = async (id: string): Promise<{ url: string }> => {
    return {
        url: `${API_URL}/invoices/${id}/download-sales-invoice`
    };
};

// [NEW] Convert Estimate to Proforma Invoice
// export const convertToProforma = async (id: string): Promise<Invoice> => {
//     const response = await axios.patch(`${API_URL}/invoices/${id}/proforma`, {}, getAxiosConfig());
//     return response.data.data;
// };


export const convertToProforma = async (
  id: string,
  data: { advancedEnabled: boolean; additionalAmount: number }
): Promise<Invoice> => {
  const response = await axios.patch(
    `${API_URL}/invoices/${id}/proforma`,
    data,
    getAxiosConfig()
  );
  return response.data.data;
};  

export const getTaxInvoicePreviewUrl = async (
    id: string
): Promise<{ url: string }> => {

    return {
        url: `${API_URL}/invoices/${id}/download-tax-invoice`
    };
};

